### ISSUE TITLE
Save and Cancel Buttons

### ISSUE THREAD

**Issue by kirontoo** [kartsims/mechdb#19]
Instead of having buttons fixed at the top or bottom of the page, it would be cool if we had the buttons stick at the upper right hand corner and stay there as we scroll down the form.

With this feature, the user wouldn't have to either scroll all the way to the top or the bottom just to save the data.

**Comment by kartsims** [comment]
We haven't talked about this in a while so I went ahead and deployed the change. Please lmk your thought @kirontoo and @D1R2 , especially if we want to revert them.

In the future we will have a test environment for this kind of features that need discussion...
