### ISSUE TITLE
Contributors reputation

### ISSUE THREAD

**Issue by kartsims** [kartsims/mechdb#22]
The website could use a reputation system, that could help identify the best contributors (and eventually promote them as "verified users")

My proposal is to go with the following:

- Rep is counted in "points" (as reddit karma)
- Each contribution that has been approved triggers a rep increase (amount to be determined)
- Admins also have a separate rep count for moderating others

What do you think of this @D1R2 @ReeceJones @kirontoo ?

If we go this way, the question that will immediately come up is : how can we count the reputation?

Suggestion:
- An item addition = +5 points for keyboards, +3 points for switches, +4 points for keycaps
- Edition = +1 point per field updated (or photo added)

Admins:
- Edit moderation = +1 point

Reputation would be displayed on the user's profile, and could even trigger an automatic update to the "verified user" status (when a user gets XX rep, (s)he gets promoted to "verified")

**Comment by kartsims** [comment]
Hey @ReeceJones are you working on the other features/checkboxes orwould you like me to give it a go?

**Comment by ReeceJones** [comment]
@kartsims Go for it. I was trying to find a good way of integrating the leaderboard with the actual values, but I'm not too familiar with vue, so it was not elegant at all.

**Comment by kartsims** [comment]
Done today:

- users now have their own reputation points assigned
- better render of edits (especially when there are differences to be highlighted between before and after)
- calculated reputation points given for each edits, and displayed them in the lists (on the admins page, and on user's profile)

There should only be the leaderboard left now 👍 and some calculations to attribute rep points only when the edit has been approved

**Comment by kartsims** [comment]
Done
