### ISSUE TITLE
Formatting Bar for text field

### ISSUE THREAD

**Issue by Vloshko** [kartsims/mechdb#38]
- Block Quotes not showing after saving.
- Attempting to add a link deletes everything in text field.
- `<li>` not inheriting `list-style-type: disc` from `<ul>` causing no bullet points to appear after saving.

**Comment by kartsims** [comment]
Fixed block quotes and list bullets

I could not reproduce this one:

> Attempting to add a link deletes everything in text field.

Could you elaborate? Maybe run tests in different situations to eventually identify the scenario in which this is happening

**Comment by Vloshko** [comment]
Link issue seems to work fine now. Unable to duplicate
