### ISSUE TITLE
Order form with 'default' fields first & Differentiate Highly Suggested from bonus fields

### ISSUE THREAD

**Issue by D1R2** [kartsims/mechdb#4]
Defaults will be the most used (and the ones we want filled out the most so the default display tables don't look empty) so I think they should be bundled together at the top of the form and some sort of indication should be given that they are highly suggested.

**Comment by kartsims** [comment]
@D1R2 are you happy with the current state? Can you make a design proposal (on photoshop or maybe tinker with the devtools to make something that would look like what you are expecting)?
