### ISSUE TITLE
Additional Parts

### ISSUE THREAD

**Issue by Vloshko** [kartsims/mechdb#40]
In addition to what you already have available for adding new Keyboards, Keycaps, & Switches add the following sections:

- Springs
- Stabilizers
- Switch Lube
- Stabilizer grease/lube
- Switch Gap Film/polycarbonate/vinyl
- PCB
- Cases
- Artisans

**Comment by kartsims** [comment]
Could you provide some details on the fieds you would expect for each dataset (dataset = type of part) ?

We have developed the first ones based on [this google document](https://docs.google.com/spreadsheets/d/1Ho6v42QT7bl-Hg-23zYNg6JDmSxEaYZQnYixYRnKddg/edit?usp=sharing), feel free to update it with your thoughts

**Comment by Vloshko** [comment]
added a few

**Comment by kartsims** [comment]
Focusing on keyboards for now
