### ISSUE TITLE
Keyboard Features: add "bluetooth type" / "per key lighting" / "socket type"

### ISSUE THREAD

**Issue by samoksner** [kartsims/mechdb#48]
In the keyboard entry form, under **Features**, we should add options for:

**Types of bluetooth** v3.0, 4.0, 4.1
**per key lighting** and include an sub-option for **RGB**
next to **hotswappable** add sub-options for **Khail socket** or **Outemu only**

**Comment by kartsims** [comment]
Could you please explain the hotswappable bit, I don't know about this...

When a PCB is hotswappable, it may be restricted to Khail only? Or Outemu only?

**Comment by kirontoo** [comment]
there are different ways you can make a pcb hotswapple. For example, kaihl hotswap sockets or Holtites. They have different sized holes for the switch pins. And some switches have pins that are thicker than others. Because of this, some switches are not compatible

**Comment by kartsims** [comment]
Thanks!

Here are some options I found online:
- Kailh
- Outemu
- Holtites
- Panda
- Mill-Max

I guess that should be enough to start with.

**Comment by kartsims** [comment]
@samoksner the requested changes have been deployed on the website 🎉
