### ISSUE TITLE
Multiple profiles for keycaps

### ISSUE THREAD

**Issue by ethanmsmith** [kartsims/mechdb#50]
e.g. mt3/SA godspeed

**Comment by kartsims** [comment]
Hi @ethanmsmith,

Thanks for uploading this content and opening the issue :)

This is an interesting suggestion however in the case of Godspeed for instance, I think it would make sense to have two separate pages. Reason being that both sets have had different GBs, and also don't share the same specifications (materials, colorways, etc.)

Also I have just fixed an issue with the duplicate names. If two names "collide" then only one of the two webpages would show up. There is now an error message that is displayed when this happens.

**Comment by kartsims** [comment]
Just realized that the issue may have been about the duplicate names collision since the 2nd webpage was not accessible...
